name: Satfera Backend Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.20.0"

      - name: Install & Build Backend
        run: |
          cd backend
          npm install
          npm run build

      - name: Install & Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to Production via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"

            # Load global npm & pm2
            export PATH="$HOME/.npm-global/bin:$PATH"
            export PATH="/usr/local/bin:/usr/bin:$PATH"

            echo "üöÄ Pulling latest changes on VPS..."
            cd basita/Satfera/backend

            git pull origin main

            npm install
            npm run build

            pm2 reload all || pm2 start npm --name "Satfera" -- start

            cd ..
            cd frontend
            npm install
            npm run build
            sudo cp -r dist/* /var/www/satfera-frontend/
            sudo systemctl reload nginx

      - name: Notify Deployment Success
        if: success()
        run: echo "üöÄ Deployment to production was successful!"

      - name: Notify Deployment Failure
        if: failure()
        run: echo "‚ùå Deployment to production failed."
